title: WayWise(R) Docs
description: Documentation for WayWise and WayWiseR
theme: just-the-docs

url: https://rise-dependable-transport-systems.github.io/waywise-docs

aux_links:
  "RISE DTS on GitHub": https://github.com/RISE-Dependable-Transport-Systems
